### PR TITLE
WID-67: Added checkbox Multi-Color for channel colors

### PR DESCRIPTION
**Pull request by Zumitify**
WID-67: Added checkbox Multi-Color for channel colors
JIRA: [https://req.thevirtualbrain.org/browse/WID-67](https://req.thevirtualbrain.org/browse/WID-67)
- Added a checkbox called "Multi-Color" that toggles on/off the channel colors.
- Default color is black.
- Added a function `add_colors()` that assigns colors to each of the channels from a pool of 10 different colors.
- Modified the function `_update_fig()` to check the value of the "Multi-Color" checkbox before updating the plot.

In Progress:
- [x] Add unit testing details/screenshots.
- [x]  Resolve commit builds [failing](https://github.com/Zumitify/tvb-widgets/actions/runs/4816162916/jobs/8575524531).
Unit testing video: 

https://user-images.githubusercontent.com/68635988/234774513-789b41b2-42f9-4ae3-a32c-4937a55b84b2.mp4

### CODE REVIEW

**Comment by liadomide** [comment]
The Sonar check failure is a known issue, not related to your changes. Pls do not spend time with it.

**Comment by romina1601** [comment]
Thanks, @Zumitify. Here are some issues that I found so far:
1. I noticed there is a problem when using 'Unselect all': we are left with some artifacts on the plot and it should be completely empty (see the green lines in the screenshot below). Also, after clicking on 'Unselect all' and unchecking the 'Multi-color' checkbox, it seems that the 'Select all' option is broken, so I think you should look into that as well.
Screenshot 2023-05-08 174317
2. Please test this feature with **tsr2** as well (see the 4th code cell from the TimeSeriesTVB.ipynb notebook). This is a time series where you can select from multiple state variables. If 'Multi-color' is checked and then I select another State var. from the dropdown, the new plot is black. This wouldn't be a problem, but the 'Multi-color' checkbox remains selected. So, when 'Multi-color' is checked and the State var. is changed either plot the new plot using colors, or uncheck the 'Multi-color' checkbox.
3. Usually, when you click on a signal in a plot, it gets colored in grey. But if the plot is multi-colored, clicking on a signal does not change its color. I think the channels should be colored in grey when we click on them, regardless if the plot is multi-colored or not.

**Comment by Zumitify** [comment]
Thanks for the feedback @romina1601. I will look into these points.

**Comment by romina1601** [comment]
> Thanks, @Zumitify. Here are some issues that I found so far:
> 
> 1. I noticed there is a problem when using 'Unselect all': we are left with some artifacts on the plot and it should be completely empty (see the green lines in the screenshot below). Also, after clicking on 'Unselect all' and unchecking the 'Multi-color' checkbox, it seems that the 'Select all' option is broken, so I think you should look into that as well.
>        Screenshot 2023-05-08 174317
> 
> 2. Please test this feature with **tsr2** as well (see the 4th code cell from the TimeSeriesTVB.ipynb notebook). This is a time series where you can select from multiple state variables. If 'Multi-color' is checked and then I select another State var. from the dropdown, the new plot is black. This wouldn't be a problem, but the 'Multi-color' checkbox remains selected. So, when 'Multi-color' is checked and the State var. is changed either plot the new plot using colors, or uncheck the 'Multi-color' checkbox.
> 
> 3. Usually, when you click on a signal in a plot, it gets colored in grey. But if the plot is multi-colored, clicking on a signal does not change its color. I think the channels should be colored in grey when we click on them, regardless if the plot is multi-colored or not.

Regarding point 1., to reproduce the problem with the green lines, make sure that you check the "Multi-color" checkbox before clicking on "Unselect all". Otherwise you won't see the problem.

**Pull request closed without merging**
