### PR TITLE
[WID-69] Support for EDF File Data in TSWidget

### PR DESCRIPTION
**Pull request by peeplika**

### CODE REVIEW

**Comment by peeplika** [comment]
This PR addresses WID-69 by adding support for adding data to TSWidget in form of EDF files.
While the issue mentioned writing a WrapperEDF class, I found that we can retrieve data from EDF files directly as NumPy arrays, making it compatible with WrapperNumpy. However, I acknowledge that there may be aspects I've overlooked or that this approach may not align with the project's coding style.
Any feedback is appreciated so that I can proceed accordingly. Thank you!

**Comment by liadomide** [comment]
@peeplika I think @romina1601 can have a better judge on the project coding style.

To me, this PR looks decent, but do you think it is possible to also write a unit-test with the new EDF related code ?
Also: can you tell us where did you find the test EDF file? is its license compatible for copying it here ?

**Comment by romina1601** [comment]
Hi @peeplika ,
The code looks good, however I think it would be better to create a separate Wrapper for the EDF file (maybe one that extends WrapperNumpy?), just to keep it consistent with what we have so far.

**Comment by peeplika** [comment]
Hello @liadomide @romina1601 Thanks for the feedback.
I have now created a seperate Wrapper for edf data and also added a test for it.
I took the test file from here -https://github.com/beacon-biosignals/EDF.jl/tree/main/test/data

**Comment by romina1601** [comment]
Hi @peeplika ,
Thank you for your work on this issue. After discussing with @liadomide , we realized that if we allow the user to specify the path of a file as data argument for the `plot_timeseries` method, this would not be consistent with how our widgets work, because our widgets usually accept an in-memory object.
For this reason, I will edit this PR to merge it into another development branch from our repo (so not directly into `main` branch), I will make some changes to your code and then finally merge it into `main`. In this way, all your commits will be present into our repo and I can implement the necessary changes. 😊

**Pull request merged**
